// Code generated by MockGen. DO NOT EDIT.
// Source: domain/repository.go

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	context "context"
	reflect "reflect"

	models "github.com/boretsotets/e-commerce-platform/product-service/internal/domain/models"
	gomock "github.com/golang/mock/gomock"
)

// MockProductRepository is a mock of ProductRepository interface.
type MockProductRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProductRepositoryMockRecorder
}

// MockProductRepositoryMockRecorder is the mock recorder for MockProductRepository.
type MockProductRepositoryMockRecorder struct {
	mock *MockProductRepository
}

// NewMockProductRepository creates a new mock instance.
func NewMockProductRepository(ctrl *gomock.Controller) *MockProductRepository {
	mock := &MockProductRepository{ctrl: ctrl}
	mock.recorder = &MockProductRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductRepository) EXPECT() *MockProductRepositoryMockRecorder {
	return m.recorder
}

// BatchChangeStock mocks base method.
func (m *MockProductRepository) BatchChangeStock(ctx context.Context, items []*models.StockChangeItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchChangeStock", ctx, items)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchChangeStock indicates an expected call of BatchChangeStock.
func (mr *MockProductRepositoryMockRecorder) BatchChangeStock(ctx, items interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchChangeStock", reflect.TypeOf((*MockProductRepository)(nil).BatchChangeStock), ctx, items)
}

// CheckProductExsistence mocks base method.
func (m *MockProductRepository) CheckProductExsistence(ctx context.Context, name string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckProductExsistence", ctx, name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckProductExsistence indicates an expected call of CheckProductExsistence.
func (mr *MockProductRepositoryMockRecorder) CheckProductExsistence(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckProductExsistence", reflect.TypeOf((*MockProductRepository)(nil).CheckProductExsistence), ctx, name)
}

// DeleteProduct mocks base method.
func (m *MockProductRepository) DeleteProduct(ctx context.Context, productID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProduct", ctx, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProduct indicates an expected call of DeleteProduct.
func (mr *MockProductRepositoryMockRecorder) DeleteProduct(ctx, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProduct", reflect.TypeOf((*MockProductRepository)(nil).DeleteProduct), ctx, productID)
}

// GetById mocks base method.
func (m *MockProductRepository) GetById(ctx context.Context, id int64) (*models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(*models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockProductRepositoryMockRecorder) GetById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockProductRepository)(nil).GetById), ctx, id)
}

// GetList mocks base method.
func (m *MockProductRepository) GetList(ctx context.Context, offset, limit int32) ([]*models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetList", ctx, offset, limit)
	ret0, _ := ret[0].([]*models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetList indicates an expected call of GetList.
func (mr *MockProductRepositoryMockRecorder) GetList(ctx, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockProductRepository)(nil).GetList), ctx, offset, limit)
}

// InsertNewProduct mocks base method.
func (m *MockProductRepository) InsertNewProduct(ctx context.Context, name string, price float64, stock int32) (*models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertNewProduct", ctx, name, price, stock)
	ret0, _ := ret[0].(*models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertNewProduct indicates an expected call of InsertNewProduct.
func (mr *MockProductRepositoryMockRecorder) InsertNewProduct(ctx, name, price, stock interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertNewProduct", reflect.TypeOf((*MockProductRepository)(nil).InsertNewProduct), ctx, name, price, stock)
}

// UpdateStock mocks base method.
func (m *MockProductRepository) UpdateStock(ctx context.Context, id int64, delta int32) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStock", ctx, id, delta)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStock indicates an expected call of UpdateStock.
func (mr *MockProductRepositoryMockRecorder) UpdateStock(ctx, id, delta interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStock", reflect.TypeOf((*MockProductRepository)(nil).UpdateStock), ctx, id, delta)
}
