CREATE TABLE orders
ADD COLUMN order_id BIGSERIAL PRIMARY KEY,
ADD COLUMN client_id BIGINT NOT NULL,
ADD COLUMN "Status" TEXT NOT NULL,
ADD COLUMN ShippingAddress TEXT,
ADD COLUMN created_at TIMESTAMP DEFAULT now(),
ADD COLUMN updated_at TIMESTAMP DEFAULT now();