CREATE TABLE order_items
ADD COLUMN id BIGSERIAL PRIMARY KEY,
ADD COLUMN order_id BIGSERIAL NOT NULL REFERENCES orders(order_id),
ADD COLUMN product_id BIGINT NOT NULL,
ADD COLUMN count INT NOT NULL;
